name: Build React App Artifacts
# on: workflow_dispatch
on: push
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci 
      - name: Build the application
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ReactApp
          path: build
  
  grab_artifacts:
    needs: build_app
      runs-on: ubuntu-latest
      steps:
        - name: Fetch artifacts
          run: actions/download-artifact@v3
          with:
            name: ReactApp
            