name: Deploy React App
on:
  push:
    branches:
      - 'master'
    # paths-ignore:
    #   - '.github/workflows/*'

jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Use cache dependencies
        uses: actions/cache@v3
        with:
          path: ~./npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test the application
        run: npm run test
      - name: Run lint
        run: npm run lint
  
  build_app:
    runs-on: ${{ matrix.os }}
    needs: test_app
    strategy:
      matrix:
        node-version: [14.17.0, 16]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use cache dependencies
        uses: actions/cache@v3
        with:
          path: ~./npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build