name: Deploy React App
on:
  push:
    branches:
      - master
jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test the application
        run: npm run test
      - name: Run lint
        run: npm run lint
  build_app:
    runs-on: ubuntu-latest
    needs: test_app
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build the application
        run: npm run build